name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          cache-dependency-path: "pyproject.toml"
          python-version: 3.11.9
          cache: pip

      - name: Install dependencies
        run: |
          pip install .[aliyun]

      - name: Build package
        run: |
          python -m build

      - name: Generate Changelog
        run: |
          python ./tool/gen_changelog.py

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          files: |
            dist/*
